language: shell
sudo: required

services:
- docker

arch:
  packages:
    - python
    - python-isort
    - python-pytest
    - python-pytest-cov
    - python-sqlalchemy
    - python-sqlalchemy-continuum
    - python-flask
    - python-flask-sqlalchemy
    - python-flask-wtf
    - python-flask-login
    - python-flask-migrate
    - python-flask-talisman
    - python-requests
    - python-scrypt
    - pyalpm
    - sqlite
  script:
    - python3 -m py_compile $(git ls-files '*.py')
    - make test

script: 'curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash'

notifications:
  irc:
    channels:
      - 'ircs://chat.freenode.net:7070/#archlinux-security'
    template:
      - "[\x0313%{repository_name}\x0f] \x02\x0302%{result}\x0f \x0306%{branch}\x0f \x0314%{commit}\x0f \x0300%{author}\x0f: %{commit_subject}"
      - "Commit changes: \x0302%{compare_url}\x0f"
      - " Build details: \x0302%{build_url}\x0f"
    on_success: always
    on_failure: always
    use_notice: false
    skip_join: false

# vim: ft=yaml ts=2 sw=2 et:
